version: '3.8'

services:
  find-artek-app-main:
    image: vicmrp/find-artek-app-main

    volumes:
      - .:/usr/src/project
      - ./shared-project-data:/mnt/shared-project-data
      
    stdin_open: true
    tty: true
    restart: always    
    
    command: bash -c 'cd /usr/src/project/app-main && rm -rf venv && python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8121'
  
    networks:
      - shared_network

  find-artek-httpd-service:
    image: httpd:2.4
    stdin_open: true
    tty: true
    restart: always


    volumes:
      - ./shared-project-data:/mnt/shared-project-data
      - ./httpd-service/data/virtualhosts:/usr/local/apache2/conf/virtualhosts
      - ./httpd-service/data/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - shared_network
      


### postgresql ###
  find-artek-db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find-artek-1
    volumes:
      - find-artek-postgresql:/var/lib/postgresql/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - shared_network

  find-artek-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "victor.reipur@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "vicmrp"
    # ports:
      # - 5050:80
    depends_on:
      - find-artek-db
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - find-artek-pgadmin:/var/lib/pgadmin
    networks:
      - shared_network
### postgresql ###



  find-artek-mariadb-service:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    volumes:
      - find-artek-mariadb:/var/lib/mysql
      - ../mariadb-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared_network



  find-artek-phpmyadmin-service:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - "5010:80"
      environment:
        PMA_HOST: find-artek-mariadb-service
        MYSQL_ROOT_PASSWORD: mariadb
        MYSQL_USER: mariadb
        MYSQL_PASSWORD: mariadb
      volumes:
        - ../phpmyadmin-service/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
      networks:
        - shared_network


volumes:
  find-artek-postgresql:
    external: true
  find-artek-pgadmin:
    external: true
  find-artek-mysql:
    external: true

networks:
  shared_network:
    external: true

