services:
  webapp_find-artek:
    restart: always
    container_name: webapp_find_artek
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - /mnt/Qdrev-arctic-web-data/staticfiles/find_artek_static:/mnt/shared-project-data
    ports:
      - "8099:8099"
    stdin_open: true
    tty: true
    #command: bash -c 'cd /app && python manage.py runserver 0.0.0.0:8099 --settings find_artek.development_settings'
    networks:
      - docker_default


  # CONSIDER HOW TO INSTANTIATE DATABASE!!!
  find-artek-mariadb-service:
    restart: always
    image: mariadb:11.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} # find-artek-django
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - find-artek-mariadb:/var/lib/mysql
      - ./docker/mariadb-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - docker_default


  find-artek-phpmyadmin-service:
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "6001:80"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/phpmyadmin-service/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    networks:
      - docker_default

volumes:
  find-artek-mariadb:
    external: true

# Ensure that we attach to network used by the nginx reverse proxy
networks:
  docker_default:
    external: true
