version: '3.8'

services:
  # du behøver ikke namespace her, du gør docker for dig, du kan bare kalde den app-main
  find-artek-app-main:
    image: vicmrp/find-artek-app-main

    volumes:
      - .:/usr/src/project
      - ./shared-project-data:/mnt/shared-project-data
      
    stdin_open: true
    tty: true
    restart: always    
    # RUN THIS IN PRODUCTION
    # command: bash -c 'cd /usr/src/project/app-main && rm -rf venv && python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000'

    # RUN THIS IN DEVELOPMENT
    command: bash -c 'cd /usr/src/project/app-main && rm -rf venv && python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt && sleep infinity'

    networks:
      - shared_network


  find-artek-db:
    image: postgis/postgis:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find-artek-1
    volumes:
      - find-artek-postgresql:/var/lib/postgresql/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - shared_network

  find-artek-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "victor.reipur@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "vicmrp"
    # ports:
      # - 5050:80
    depends_on:
      - find-artek-db
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - find-artek-pgadmin:/var/lib/pgadmin
    networks:
      - shared_network

  # find-artek-classic:
  #   image: vicmrp/django1-6-11_python2-7-9_artek_2022-11-21-v0-2
  #   volumes:

  #     - ../shared-project-data:/mnt/shared-project-data
  #     - ../app-classic/find_artek:/usr/src/app/find_artek
    
  #   # Run this in production
  #   command: sh -c 'cd /usr/src/app/find_artek && python manage.py runserver 0.0.0.0:80'

    
#    stdin_open: true
#    tty: true
#    networks:
#      - shared_network

  find-artek-httpd-service:
    image: httpd:2.4
    stdin_open: true
    tty: true
    restart: always


    volumes:
      - ./shared-project-data:/mnt/shared-project-data
      - ./httpd-service/data/virtualhosts:/usr/local/apache2/conf/virtualhosts
      - ./httpd-service/data/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - shared_network



volumes:
  find-artek-postgresql:
    external: true
  find-artek-pgadmin:
    external: true

networks:
  shared_network:
    external: true

