version: '3.8'

services:
  find-artek-app:
    image: vicmrp/find-artek-app
    container_name: find-artek-app
    build:
      context: .
      dockerfile: Dockerfile-find-artek
    ports:
      - 8000:8000
    volumes:
      - ..:/usr/src/find_artek
      - ../app-data:/usr/src/find_artek/app-data
    #command: sleep infinity
    command: bash -c 'cd /usr/src/find_artek/app && rm -rf venv && python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000'
    # make achange 
  find-artek-db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find-artek-1
    ports:
      - 5432:5432
  
  find-artek-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "victor.reipur@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "vicmrp"
    ports:
      - 5050:80
    depends_on:
      - find-artek-db

  find-artek-classic:
    image: vicmrp/django1-6-11_python2-7-9_artek_2022-11-21-v0-2
    volumes:
      - ../app-data:/usr/src/app/app-data
      - ../app-classic/find_artek:/usr/src/app/find_artek
    command: sh -c 'cd /usr/src/app/find_artek && python manage.py runserver 0.0.0.0:80'

    # command: sleep infinity
    stdin_open: true
    tty: true



  httpd:
    image: httpd:2.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../app-data:/app-data
      - ../httpd/usr/local/apache2:/usr/local/apache2


