version: '3.8'

services:
  find-artek-app:
    # image: find-artek-app
    build:
      context: .
      dockerfile: Dockerfile-find-artek
    ports:
      - 8000:8000
    volumes:
      - ..:/usr/src/find_artek
    command: sleep infinity

  find-artek-db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find-artek-1
    ports:
      - 5432:5432
  
  find-artek-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "victor.reipur@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "vicmrp"
    ports:
      - 5050:80
    depends_on:
      - find-artek-db
      